### PR TITLE
Added mutex in the rpc call setEmotion.

### LINKED ISSUE #138: setEmotion is not thread safe
I was checking the code, and I noticed that if I call setEmotion from code repeatedly, there might be race conditions. In fact, subsequent calls to ``setEmotion`` might change the values of ``isTransition`` and ``command`` while they are being used in ``updateModule``

cc @Nicogene @martinaxgloria

### PR DESCRIPTION
**Pull request by S-Dafarra**
Fixes #138 

Still need to be tested on the robot.

### CODE REVIEW

**Review by martinaxgloria — APPROVED** [review]

**Comment by martinaxgloria** [comment]
I've tried the changes on my laptop and everything seems to work properly, but it needs to be tested on ergoCub

**Comment by S-Dafarra** [comment]
The code has been tested on ergoCub. 

We noticed that sometimes, the transition does not appear. 

I checked the code and I think it is related to ``showTransition``. I will address this soon

**Comment by Nicogene** [comment]
> The code has been tested on ergoCub.
> 
> We noticed that sometimes, the transition does not appear.
> 
> I checked the code and I think it is related to `showTransition`, where I don't lock the mutex. I will address this soon

Great thanks!

**Comment by S-Dafarra** [comment]
> The code has been tested on ergoCub.
> 
> We noticed that sometimes, the transition does not appear.
> 
> I checked the code and I think it is related to `showTransition`, where I don't lock the mutex. I will address this soon

Done in https://github.com/icub-tech-iit/ergocub-software/pull/139/commits/a260c767f40a315db2a2ec9a50598669e42d02e5

With https://github.com/icub-tech-iit/ergocub-software/pull/139/commits/ab77ae809c2ddb5acbd75884de1692d1a42100ba I tried to speed up a bit the transitions, although they still take a long time to start. I suppose it is related to the loading of the images and video at runtime, but it is outside the scope of this PR.

I have tested it on ergoCub

**Review by Nicogene — APPROVED** [review]

**Comment by Nicogene** [comment]
Merged, thanks!

**Pull request merged**
