### PR TITLE
couplingXCubHandMk5: handle the param parsing with the YARP param parser generator

### PR DESCRIPTION
**Pull request by Nicogene**
This PR introduces the usage of the new [YARP param parsing generator](https://github.com/robotology/yarp/discussions/3081), moreover using this new tool allows to align this device to the good practice of avoiding using the `findGroup` clause for parsing the lists, see:
- https://github.com/robotology/yarp/discussions/3092

Unfortunately some parameters are "shared" with the gazebo controlboards so using `()` for this device breaks the parsing of the gazebo controlboards, so I would put thi on hold until we do not make the change also on gyp side (cc @traversaro)

Moreover maybe it is better that YARP 3.10 has been released

### CODE REVIEW

**Comment by traversaro** [comment]
> Moreover maybe it is better that YARP 3.10 has been released

Yes, that would be great. It would be problematic for people working on ergocub+gz-sim integration (@xela-95) if we could not release ergocub models until YARP 3.10 is released.

**Comment by Nicogene** [comment]
I have also ported all the ini in order to use the parenthesis, with this patch:

- https://github.com/robotology/gazebo-yarp-plugins/pull/681

It works fine, @traversaro probably it would be convenient to have another gyp tag

**Comment by Nicogene** [comment]
YARP 3.10.0 has been released:
- https://github.com/robotology/yarp/releases/tag/v3.10.0

Probably I would need that the conda binaries are released too.

cc @traversaro

**Comment by traversaro** [comment]
> Probably I would need that the conda binaries are released too.

Ack! See https://github.com/conda-forge/yarp-feedstock/pull/53 . I think I can do that even before https://github.com/robotology/robotology-superbuild/issues/1740, as people using conda/pixi can easily pin yarp to an earlier release, and actually release it can help in testing it.

**Comment by Nicogene** [comment]
Finally the CI is green! Merging

**Pull request merged**
