### PR TITLE
Add Gazebo Sim support

### PR DESCRIPTION
**Pull request by xela-95**
This PR introduces the support to the new [Gazebo](https://gazebosim.org).

Reference issue: https://github.com/robotology/gz-sim-yarp-plugins/issues/130

## Tools

| Tool| Version|
|--------|--------|
| CREO| 9.0.8.0|
| creo2urdf| [v0.4.6](https://github.com/icub-tech-iit/creo2urdf/releases/tag/v0.4.6) installed from binaries|
| cad-mechanics | [5d31e](https://github.com/icub-tech-iit/cad-mechanics/tree/5d31e879645c31fe5d8afae4f86c193dae1ac9e2)
| cad-libraries| [851b1](https://github.com/icub-tech-iit/cad-libraries/tree/851b197f662cc128668fb562fafd3313f5fc54fe)|

### CODE REVIEW

**Comment by xela-95** [comment]
CC @traversaro

**Comment by xela-95** [comment]
I'm thinking about where I should put the [gz-sim-yarp-plugins](https://github.com/robotology/gz-sim-yarp-plugins). 

As potential alternatives, I see:
- Add them to the existing ergoCub yaml files [ERGOCUB_all_options_gazebo](https://github.com/icub-tech-iit/ergocub-software/blob/4a7ce3a1472b16c7a3372623199c3ccbaa761a3d/urdf/creo2urdf/data/ergocub1_1/ERGOCUB_all_options_gazebo.yaml) and [ERGOCUB_all_options_minContacts](https://github.com/icub-tech-iit/ergocub-software/blob/4a7ce3a1472b16c7a3372623199c3ccbaa761a3d/urdf/creo2urdf/data/ergocub1_1/ERGOCUB_all_options_minContacts.yaml) with the pro of having the same number of output models and the con of having error logs both in gazebo-classic and gazebo since some of the plugins will not be found (I'm currently testing that these errors do not cause the simulation to stop);
- Generate a new set of ergoCub models only for the new Gazebo: in this case the existing models are left untouched and we do not have misleading errors logged by Gazebo, with the burden of having more files to maintain in the long period. 

@traversaro @Nicogene what do you think?

**Comment by traversaro** [comment]
I would go for the first option. I know that error may be confusing, but the explosion of models seems even worse. We can work with upstream to minimize the effect of this errors (see https://github.com/gazebosim/sdformat/issues/93) in the long run, but for now I would just keep one set of models, let's see what @Nicogene thinks about this.

**Comment by Nicogene** [comment]
> I would go for the first option. I know that error may be confusing, but the explosion of models seems even worse. We can work with upstream to minimize the effect of this errors (see [gazebosim/sdformat#93](https://github.com/gazebosim/sdformat/issues/93)) in the long run, but for now I would just keep one set of models, let's see what @Nicogene thinks about this.

I totally agree with it also because right now the models are generated by hand, and it would be complicated to augment the number of generated models

**Comment by xela-95** [comment]
Ok thanks! I will proceed as suggested then ✌🏻

**Comment by xela-95** [comment]
After a long day of trial & error, ergoCubGazeboV1_1 works both on gazebo-classic and gazebo!!! 🥳 

Now it's just a matter of porting these modifications to the other models.

**Comment by xela-95** [comment]
@traversaro looking at the table in https://github.com/icub-tech-iit/ergocub-software/tree/master/urdf/creo2urdf/data/ergocub1_1 there should be for each version of ergoCub a different pair of `.yml` and `.csv` files, while now there is only a single `.csv`: [ERGOCUB_joint_all_parameters.csv]( https://github.com/icub-tech-iit/ergocub-software/blob/4a7ce3a1472b16c7a3372623199c3ccbaa761a3d/urdf/creo2urdf/data/ergocub1_1/ERGOCUB_joint_all_parameters.csv). Is this correct?

**Comment by traversaro** [comment]
> @traversaro looking at the table in https://github.com/icub-tech-iit/ergocub-software/blob/4a7ce3a1472b16c7a3372623199c3ccbaa761a3d/urdf/creo2urdf/data/ergocub1_1/README.md, there should be for each version of ergoCub a different pair of `.yml` and `.csv` files, while now there is only a single `.csv`: [ERGOCUB_joint_all_parameters.csv](https://github.com/icub-tech-iit/ergocub-software/blob/4a7ce3a1472b16c7a3372623199c3ccbaa761a3d/urdf/creo2urdf/data/ergocub1_1/ERGOCUB_joint_all_parameters.csv). Is this correct?

Yes, I think that was just a typo, feel free to correct.

**Comment by xela-95** [comment]
I finished porting the main changes both to version 0 and 1 of ergoCub. I'm having some issue while trying to import the models of ergoCub version 0 (the ones generated from the yaml files in https://github.com/xela-95/ergocub-software/tree/feature/add-gz-sim-support/urdf/creo2urdf/data/ergocub1_0). It is also strange that the URDF generated with CREO is a lot different than the previous version, while for the models of version 1 the diff in the urdf are just the ones I added in the yaml.

**Comment by traversaro** [comment]
> It is also strange that the URDF generated with CREO is a lot different than the previous version, while for the models of version 1 the diff in the urdf are just the ones I added in the yaml.

I guess this small numeric errors (they seems all to be <= 1e-10 can be due):
* Minor changes in creo2urdf dependencies
* Minor changes in creo version
* Minor changes in version of cad-mechanics used

Anyhow, unless we start locking all of these variables (that at the moment is not feasible, I guess) we can safely ignore them.

**Comment by traversaro** [comment]
> I'm having some issue while trying to import the models of ergoCub version 0 (the ones generated from the yaml files in https://github.com/xela-95/ergocub-software/tree/feature/add-gz-sim-support/urdf/creo2urdf/data/ergocub1_0).

Which errors? What I noticed is that you also added the controlboard of the hands, but those require coupling that is currently not supported in gz-sim-yarp-plugins, is that intentional?

**Comment by traversaro** [comment]
> Anyhow, unless we start locking all of these variables (that at the moment is not feasible, I guess) we can safely ignore them.

Note that something that we can easily is at least to document in each PR that changes the models the version numbers of Creo, `creo2urdf` (reporting if compiled from sources or if the .dll from the release is used) and the checkout of cad-mechanics and cad-libraries used.

**Comment by traversaro** [comment]
By the way, there are also some tests failures in the tests:
~~~
 Test project /home/runner/work/ergocub-software/ergocub-software/build
    Start 1: ergoCubGazeboV1ConsistencyCheck
1/4 Test #1: ergoCubGazeboV1ConsistencyCheck .....***Failed    0.02 sec
ergocub-model-test error:r_index_dist got direction of  x -0.947223 y -0.290266 z -0.136064 instead of expected  x 0.947223 y 0.290266 z 0.136064

    Start 2: ergoCubGazeboV1_1ConsistencyCheck
2/4 Test #2: ergoCubGazeboV1_1ConsistencyCheck ...   Passed    0.03 sec
    Start 3: ergoCubSN000ConsistencyCheck
3/4 Test #3: ergoCubSN000ConsistencyCheck ........***Failed    0.03 sec
ergocub-model-test error:r_index_dist got direction of  x -0.947223 y -0.290266 z -0.136064 instead of expected  x 0.947223 y 0.290266 z 0.136064

    Start 4: ergoCubSN001ConsistencyCheck
4/4 Test #4: ergoCubSN001ConsistencyCheck ........   Passed    0.03 sec
~~~

That is quite strange, it seems like the kind of errors we had with simmechanics-to-urdf, where the direction of the axis was randomly changing. Anyhow, given the problems with the `ergoCubSN000` and `ergoCubGazeboV1`, probably we can drop them from the first PR?

**Comment by xela-95** [comment]
> > It is also strange that the URDF generated with CREO is a lot different than the previous version, while for the models of version 1 the diff in the urdf are just the ones I added in the yaml.
> 
> I guess this small numeric errors (they seems all to be <= 1e-10 can be due):
> 
>     * Minor changes in creo2urdf dependencies
> 
>     * Minor changes in creo version
> 
>     * Minor changes in version of cad-mechanics used
> 
> 
> Anyhow, unless we start locking all of these variables (that at the moment is not feasible, I guess) we can safely ignore them.

Yes I agree for the numeric errors. But other than that there are other modifications that I'm investigating, like the name of the `.stl` files have been changed,  and also material and collision attributes.

**Comment by xela-95** [comment]
> > I'm having some issue while trying to import the models of ergoCub version 0 (the ones generated from the yaml files in https://github.com/xela-95/ergocub-software/tree/feature/add-gz-sim-support/urdf/creo2urdf/data/ergocub1_0).
> 
> Which errors? What I noticed is that you also added the controlboard of the hands, but those require coupling that is currently not supported in gz-sim-yarp-plugins, is that intentional?

Sorry I added that without thinking to the missing coupling features, I will remove them to all models then. 

Maybe it's also good to open an issue on gz-sim-yarp-plugins to track the plugins that ergocub-software currently misses.

**Comment by traversaro** [comment]
> Yes I agree for the numeric errors. But other than that there are other modifications that I'm investigating, like the name of the `.stl` files have been changed, and also material and collision attributes.

Ack, I guess you did not committed that? It is possible that the cad-mechanics model was changed, but the change was not propagated to the repo. It is happening for both SN000 and SN001 or just SN000? If it is just SN001, I would just drop it. To decouple the problems of "updating cad-mechanics" from the core of this, one possible strategy is just to use the cad-mechanics commit that was used to generate the version of the models currently present in the repo. For `ergoCubSN001/ergoCubGazeboV1_1*` is is quite recent (https://github.com/icub-tech-iit/ergocub-software/pull/226), perhaps @Nicogene remember which cad-mechanics checkout was used. For the other models https://github.com/icub-tech-iit/ergocub-software/pull/220 it was older, perhaps @Nicogene has some hint of the cad-mechanics source models used, but as I mentioned I would drop `ergoCubSN000/ergoCubGazeboV1` from the initial PR if they are giving problems.

**Comment by xela-95** [comment]
> Ack, I guess you did not committed that? It is possible that the cad-mechanics model was changed, but the change was not propagated to the repo. It is happening for both SN000 and SN001 or just SN000? If it is just SN001, I would just drop it. To decouple the problems of "updating cad-mechanics" from the core of this, one possible strategy is just to use the cad-mechanics commit that was used to generate the version of the models currently present in the repo. For `ergoCubSN001/ergoCubGazeboV1_1*` is is quite recent (#226), perhaps @Nicogene remember which cad-mechanics checkout was used. For the other models #220 it was older, perhaps @Nicogene has some hint of the cad-mechanics source models used, but as I mentioned I would drop `ergoCubSN000/ergoCubGazeboV1` from the initial PR if they are giving problems.

The models that change significantly are the tree coming from the `ergoCub1_0` folder.

**Comment by traversaro** [comment]
> The models that change significantly are the three coming from the `ergoCub1_0` folder.

Perfect, I would discard them for now. Those are also the one for which tests are failing.

**Comment by xela-95** [comment]
> > The models that change significantly are the three coming from the `ergoCub1_0` folder.
> 
> Perfect, I would discard them for now. Those are also the one for which tests are failing.

OK! also with @Nicogene we agreed that I will maintain the modifications to the `yaml` files in case in future someone will need to generate new `urdf` versions, but for this PR I will discard them.

**Comment by Nicogene** [comment]
> perhaps @Nicogene remember which cad-mechanics checkout was used. For the other models https://github.com/icub-tech-iit/ergocub-software/pull/220 it was older, perhaps @Nicogene has some hint of the cad-mechanics source models used, but as I mentioned I would drop ergoCubSN000/ergoCubGazeboV1 from the initial PR if they are giving problems.


It may be `dfedc37d82224bc627083e0fc0fb9e17d7bcf8ae` but not 100% sure, I don't update `cad-mechanics` frequently

> That is quite strange, it seems like the kind of errors we had with simmechanics-to-urdf, where the direction of the axis was randomly changing. Anyhow, given the problems with the ergoCubSN000 and ergoCubGazeboV1, probably we can drop them from the first PR?

About this point I aligned w/ @xela-95 T2T, the urdf of ergoCub 1.0/SN000 has never been generated with creo2urdf, in the past it has been generated w/ `simmechanics_to_urdf` doing the procedure CREO9->CREO7 for the issues we know, and since it had a high-cost fix on CAD side we used to do patches via software:
- https://github.com/icub-tech-iit/ergocub-software/issues/106

All this time I have been keeping up-to-date the yaml to be usable when we will regenerate the model via creo2urdf, but for sure before it required fixes on simulation model CAD that right now we do not have the workforce to do.

So I suggested to @xela-95 to commit also the changes to the 1.0/SN000 yaml and add by hand the blobs to the 1.0/SN000 urdf.
The errors you are getting are probably related to some wrong `reverseRotationAxis`.

cc @maggia80 @pattacini

**Comment by traversaro** [comment]
> About this point I aligned w/ @xela-95 T2T, the urdf of ergoCub 1.0/SN000 has never been generated with creo2urdf, in the past it has been generated w/ `simmechanics_to_urdf` doing the procedure CREO9->CREO7 for the issues we know, and since it had a high-cost fix on CAD side we used to do patches via software:
> 
>     *

Can you add this information in https://github.com/icub-tech-iit/ergocub-software/tree/master/urdf/creo2urdf/data/ergocub1_0#readme ? Personally I lost track of this, and it may be helpful for future users to actually document how the ergocub1_0 models are actually generated.

**Comment by xela-95** [comment]
> Note that something that we can easily is at least to document in each PR that changes the models the version numbers of Creo, `creo2urdf` (reporting if compiled from sources or if the .dll from the release is used) and the checkout of cad-mechanics and cad-libraries used.

Added tool versions

**Comment by Nicogene** [comment]
@xela-95 @traversaro I have added a Pull request template but I am not sure it works:
- https://github.com/icub-tech-iit/ergocub-software/blob/master/.github/PULL_REQUEST_TEMPLATE/pull_request_template.md

**Comment by Nicogene** [comment]
> > About this point I aligned w/ @xela-95 T2T, the urdf of ergoCub 1.0/SN000 has never been generated with creo2urdf, in the past it has been generated w/ `simmechanics_to_urdf` doing the procedure CREO9->CREO7 for the issues we know, and since it had a high-cost fix on CAD side we used to do patches via software:
> > ```
> > *
> > ```
> 
> Can you add this information in [`master`/urdf/creo2urdf/data/ergocub1_0#readme](https://github.com/icub-tech-iit/ergocub-software/tree/master/urdf/creo2urdf/data/ergocub1_0?rgh-link-date=2024-03-28T09%3A43%3A16Z#readme) or [`master`?tab=readme-ov-file#urdf-generation](https://github.com/icub-tech-iit/ergocub-software/tree/master?tab=readme-ov-file&rgh-link-date=2024-03-28T09%3A43%3A16Z#urdf-generation) ? Nothing too complex, just to avoid that in the future people loose time to try to use `creo2urdf` with `ergocub1_0` . Personally I lost track of this, and it may be helpful for future users to actually document how the ergocub1_0 models are actually generated.

I added this info in the relative README
- https://github.com/icub-tech-iit/ergocub-software/blob/master/urdf/creo2urdf/data/ergocub1_0/README.md

**Comment by traversaro** [comment]
Thanks!

**Comment by xela-95** [comment]
Ok now the PR is ready for the review :)

**Comment by xela-95** [comment]
Rebased on master

**Review by traversaro — APPROVED** [review]
Thanks a lot @xela-95 !

**Review by Nicogene — APPROVED** [review]
I didn't have the chance to test it but if this does not interfere with gazebo classic we can merge it

**Comment by traversaro** [comment]
> I didn't have the chance to test it but if this does not interfere with gazebo classic we can merge it

We are in process of adding support in robotology-superbuild and conda-forge for gz-sim-yarp-plugins, once it is ready it should be easy to check: 
* https://github.com/robotology/gz-sim-yarp-plugins/issues/131
* https://github.com/robotology/gz-sim-yarp-plugins/issues/132

**Pull request merged**
