### PR TITLE
Fix misalignment between feet soles

### PR DESCRIPTION
**Pull request by mfussi66**
This PR aims to fix: https://github.com/icub-tech-iit/ergocub-software/issues/23

The exported material from the CAD is committed.

### CODE REVIEW

**Comment by Nicogene** [comment]
Seems that something went wrong in the generation:

```
     Start 1: ergoCubGazeboV1ConsistencyCheck
1/2 Test #1: ergoCubGazeboV1ConsistencyCheck ...***Failed    0.02 sec
ergocub-model-test error: r_knee is not revolute 

    Start 2: ergoCubSN000ConsistencyCheck
2/2 Test #2: ergoCubSN000ConsistencyCheck ......***Failed    0.02 sec
ergocub-model-test error: r_knee is not revolute 
```

**Comment by Nicogene** [comment]
For some reason `r_knee` is exported as weld

```xml
      <SimpleJoint>
        <name>"SIM_ECUB_R_UPPER_LEG--SIM_ECUB_R_LOWER_LEG"</name>
        <nodeID>"115:-:116"</nodeID>
        <status>""</status>
        <base>
          <JointSide>
            <name>""</name>
            <connection>
              <Frame ref="35"></Frame>
            </connection>
          </JointSide>
        </base>
        <follower>
          <JointSide>
            <name>""</name>
            <connection>
              <Frame ref="36"></Frame>
            </connection>
          </JointSide>
        </follower>
        <primitives>
          <Primitive>
            <name>"weld"</name>
            <nodeID>""</nodeID>
            <referenceFrame>"WORLD"</referenceFrame>
            <axis>0.57735,0.57735,0.57735</axis>
          </Primitive>
        </primitives>
      </SimpleJoint>
      <SimpleJoint>
```

cc @salvi-mattia @Mick3Lozzo

**Comment by Mick3Lozzo** [comment]
> @Mick3Lozzo in order to push the simscape button, do we have to open the mech assembly in sandbox/221219\_ergoCub\_simulation\_model\_neutral\_format
> 
> or in project/simulationmodel/ecub ?

In `sandbox/221219_ergoCub_simulation_model_neutral_format` @salvi-mattia.

**Comment by salvi-mattia** [comment]
the right knee seems to be weel defined

**Comment by Nicogene** [comment]
Right now I had to manually fix the simmechanics XML for the `r_knee` exported as weld, and the missing stl for `l_wrist_1` link

- [`50237ab` (#27)](https://github.com/icub-tech-iit/ergocub-software/pull/27/commits/50237abc7f8f8c2ba0cd817120369d3f772e42e4)
- [`0200cab` (#27)](https://github.com/icub-tech-iit/ergocub-software/pull/27/commits/0200cab145a85586197cff5da7ae2342e7ef1083)

Shall we keep track in a separate issue of these glitches in the exportation from creo?

@Lawproto @mfussi66 @Mick3Lozzo @pattacini @salvi-mattia @fiorisi

**Comment by pattacini** [comment]
>Shall we keep track in a separate issue of these glitches in the exportation from creo?

Yep definitely. I'll open a dedicated issue asap.
In the meantime, you can proceed with merging the PR if everything else is fine.

**Pull request merged**
