### PR TITLE
Add live script and data for identification and tuning of fingers

### PR DESCRIPTION
**Pull request by mfussi66**
This PR aims to add a MATLAB live script that can be used for running a linear system identification of the ergocub fingers (index and middle), plus PID tuning. 

Here is the live script in pdf: [identification_tuning.pdf](https://github.com/icub-tech-iit/ergocub-software/files/11958268/identification_tuning.pdf)

Here are some plots showing the small but noticeable improvements in position tracking at different speeds:
trajectory
fingers

### CODE REVIEW

**Review by Nicogene — COMMENTED** [review]
I would rename the folder `lib` to `scripts`

**Review by pattacini — CHANGES_REQUESTED** [review]
We ought to include the C++ code used for acquiring input-output data (for identification) and for validation purposes.

**Comment by mfussi66** [comment]
> We ought to include the C++ code used for acquiring input-output data (for identification) and for validation purposes.

@pattacini done!

**Comment by pattacini** [comment]
> > We ought to include the C++ code used for acquiring input-output data (for identification) and for validation purposes.
> 
> @pattacini done!

Thanks!

**Review by pattacini — APPROVED** [review]
Nothing really blocking from merging, but we may consider introducing the use of [`arguments`](https://www.mathworks.com/help/matlab/ref/arguments.html) in MATLAB scripts to improve standardization.

What do you think @mfussi66?

**Comment by mfussi66** [comment]
> Nothing really blocking from merging, but we may consider introducing the use of [`arguments`](https://www.mathworks.com/help/matlab/ref/arguments.html) in MATLAB scripts to improve standardization.
> 
> What do you think @mfussi66?

Sure, it might delay a bit the merge since it's a new topic for me, that's all.

**Review by Nicogene — COMMENTED** [review]
I don't have a strong opinion on this, but we could add `add_subdirectory(tools)` for compiling it from the root folder.
This has the pro of compile it in the same build directory of the entire project, but the cons that this will be compiled in the CI (and then continuously supported)

**Review by pattacini — COMMENTED** [review]
Super 🚀

**Review by Nicogene — APPROVED** [review]

**Comment by pattacini** [comment]
cc @xEnVrE @S-Dafarra @GiulioRomualdi

**Pull request merged**
